project:
  type: website
  output-dir: docs

website:
  title: "jriveraprince"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: article_translations.qmd
        text: Traducciones en Espa√±ol
  google-analytics: "G-4H3MYWQGNG"
        
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

